<?php
/**
 * HCLOU-LICENSE — Web installer (5 steps wizard)
 * Cài đặt nhanh không cần CLI. Sau khi xong tạo data/installed.lock để tự khoá.
 */

@session_start();
@mkdir(__DIR__ . '/data', 0700, true);

$lockFile = __DIR__ . '/data/installed.lock';
$configLocalFile = __DIR__ . '/config.local.php';
$sqlFile = __DIR__ . '/database.sql';

// =============================================
// SELF-PROTECT — đã cài rồi thì refuse
// =============================================
if (file_exists($lockFile) && empty($_GET['force'])) {
    http_response_code(403);
    die('<!doctype html><meta charset=utf-8><title>Installed</title><body style="font-family:system-ui;background:#0d1117;color:#e6edf3;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;padding:24px;text-align:center"><div style="max-width:480px"><h2 style="color:#34d399">✓ Đã cài đặt</h2><p>HCLOU-LICENSE đã setup xong. Xoá <code>data/installed.lock</code> rồi mở <code>install.php?force=1</code> nếu muốn cài lại.</p><p style="margin-top:24px"><a href="admin/" style="color:#7c6fe0">→ Vào admin panel</a></p></div></body>');
}

// =============================================
// CSRF
// =============================================
if (empty($_SESSION['install_csrf'])) {
    $_SESSION['install_csrf'] = bin2hex(random_bytes(16));
}

// =============================================
// HELPERS
// =============================================
function h($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
function genToken($bytes = 32) { return bin2hex(random_bytes($bytes)); }

function detectSiteUrl() {
    $proto = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host  = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $path  = rtrim(dirname($_SERVER['SCRIPT_NAME'] ?? '/'), '/\\');
    return $proto . '://' . $host . $path;
}

function testDbConnection($host, $name, $user, $pass) {
    try {
        $pdo = new PDO(
            "mysql:host={$host};dbname={$name};charset=utf8mb4",
            $user, $pass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        return ['ok' => true, 'pdo' => $pdo];
    } catch (PDOException $e) {
        return ['ok' => false, 'err' => $e->getMessage()];
    }
}

function importSqlFile(PDO $pdo, $sqlFile) {
    if (!is_file($sqlFile)) return ['ok' => false, 'err' => 'File schema không tìm thấy: ' . $sqlFile];
    $sql = file_get_contents($sqlFile);
    if ($sql === false) return ['ok' => false, 'err' => 'Đọc file schema thất bại'];

    // Split by ";" + filter blank/comment
    $stmts = [];
    foreach (preg_split('/;\s*\n/', $sql) as $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '' || preg_match('/^(--|\/\*|SET |START |COMMIT|\/\*\!)/', $stmt)) continue;
        $stmts[] = $stmt;
    }
    try {
        foreach ($stmts as $s) $pdo->exec($s);
        return ['ok' => true, 'count' => count($stmts)];
    } catch (PDOException $e) {
        return ['ok' => false, 'err' => $e->getMessage()];
    }
}

function writeConfigLocal(array $data, $targetFile) {
    $lines = ["<?php", "// HCLOU-LICENSE — config.local.php (auto-generated by install.php)", "// KHÔNG commit file này vào git. Mọi secret production ở đây.", ""];
    foreach ($data as $k => $v) {
        $val = is_int($v) ? (string)$v : "'" . str_replace("'", "\\'", (string)$v) . "'";
        $lines[] = "define('{$k}', {$val});";
    }
    $lines[] = "";
    return file_put_contents($targetFile, implode("\n", $lines)) !== false;
}

// =============================================
// STEPS
// =============================================
$step = isset($_GET['step']) ? max(1, min(5, (int)$_GET['step'])) : 1;
$err = '';
$ok = '';

// Persist state across steps in session
if (!isset($_SESSION['install_data'])) $_SESSION['install_data'] = [];

// POST handler
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (($_POST['csrf'] ?? '') !== $_SESSION['install_csrf']) {
        $err = 'CSRF token sai. Reload và thử lại.';
    } else {
        $posted = (int)($_POST['step'] ?? 0);

        // STEP 2 → 3: save DB config + test
        if ($posted === 2) {
            $db = [
                'host' => trim($_POST['db_host'] ?? '127.0.0.1'),
                'name' => trim($_POST['db_name'] ?? ''),
                'user' => trim($_POST['db_user'] ?? ''),
                'pass' => (string)($_POST['db_pass'] ?? ''),
            ];
            $r = testDbConnection($db['host'], $db['name'], $db['user'], $db['pass']);
            if (!$r['ok']) {
                $err = 'Kết nối DB thất bại: ' . $r['err'];
            } else {
                $_SESSION['install_data']['db'] = $db;
                header('Location: install.php?step=3'); exit;
            }
        }

        // STEP 3 → 4: import schema
        if ($posted === 3) {
            $db = $_SESSION['install_data']['db'] ?? null;
            if (!$db) { $err = 'Mất config DB. Quay lại step 2.'; }
            else {
                $r = testDbConnection($db['host'], $db['name'], $db['user'], $db['pass']);
                if (!$r['ok']) { $err = 'Reconnect DB fail: ' . $r['err']; }
                else {
                    $imp = importSqlFile($r['pdo'], $sqlFile);
                    if (!$imp['ok']) { $err = 'Import schema lỗi: ' . $imp['err']; }
                    else {
                        $_SESSION['install_data']['imported'] = $imp['count'];
                        header('Location: install.php?step=4'); exit;
                    }
                }
            }
        }

        // STEP 4 → 5: admin user + secrets + write config
        if ($posted === 4) {
            $adminUser = trim($_POST['admin_user'] ?? '');
            $adminPass = (string)($_POST['admin_pass'] ?? '');
            $siteUrl   = trim($_POST['site_url'] ?? '');
            $siteName  = trim($_POST['site_name'] ?? 'HCLOU License');

            if (strlen($adminUser) < 3 || strlen($adminUser) > 32 || !preg_match('/^[A-Za-z0-9_]+$/', $adminUser)) {
                $err = 'Username admin: 3-32 ký tự, chỉ A-Z a-z 0-9 _';
            } elseif (strlen($adminPass) < 8) {
                $err = 'Password ít nhất 8 ký tự';
            } elseif (!preg_match('#^https?://#i', $siteUrl)) {
                $err = 'Site URL phải bắt đầu http:// hoặc https://';
            } else {
                $db = $_SESSION['install_data']['db'];
                $config = [
                    'DB_HOST'         => $db['host'],
                    'DB_NAME'         => $db['name'],
                    'DB_USER'         => $db['user'],
                    'DB_PASS'         => $db['pass'],
                    'SITE_URL'        => rtrim($siteUrl, '/'),
                    'SITE_NAME'       => $siteName,
                    'STATIC_WORD'     => genToken(16),  // 32 hex chars
                    'HMAC_SECRET'     => genToken(32),  // 64 hex chars
                    'BODY_XOR_BASE'   => genToken(24),  // 48 hex chars
                    'ADMIN_USERNAME'  => $adminUser,
                    'ADMIN_PASS_HASH' => password_hash($adminPass, PASSWORD_BCRYPT),
                ];
                if (!writeConfigLocal($config, $configLocalFile)) {
                    $err = 'Ghi config.local.php thất bại. Check permission folder.';
                } else {
                    // Lock install
                    @file_put_contents($lockFile, date('Y-m-d H:i:s') . "\n" . ($_SERVER['REMOTE_ADDR'] ?? ''));
                    $_SESSION['install_data']['summary'] = [
                        'site_url'   => $config['SITE_URL'],
                        'site_name'  => $config['SITE_NAME'],
                        'admin_user' => $config['ADMIN_USERNAME'],
                        'imported'   => $_SESSION['install_data']['imported'] ?? 0,
                    ];
                    // Wipe sensitive
                    unset($_SESSION['install_data']['db']);
                    header('Location: install.php?step=5'); exit;
                }
            }
        }
    }
}

// =============================================
// HTML
// =============================================
$siteUrlAuto = detectSiteUrl();
?>
<!doctype html>
<html lang="vi">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Cài đặt — HCLOU License</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Inter',-apple-system,'Segoe UI',sans-serif;background:#0d1117;color:#e2e8f0;min-height:100vh;padding:24px}
.wrap{max-width:560px;margin:0 auto}
.head{text-align:center;margin-bottom:24px}
.head h1{font-size:24px;font-weight:800;background:linear-gradient(135deg,#7c6fe0,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:6px}
.head p{color:#7a8499;font-size:13px}
.steps{display:flex;gap:6px;margin-bottom:18px}
.stepdot{flex:1;height:4px;background:#1e2535;border-radius:2px;transition:.3s}
.stepdot.on{background:linear-gradient(90deg,#7c6fe0,#a78bfa)}
.card{background:#161b27;border:1px solid rgba(255,255,255,.07);border-radius:18px;padding:28px 24px;box-shadow:0 24px 60px rgba(0,0,0,.4)}
h2{font-size:18px;font-weight:700;margin-bottom:16px;color:#fff}
.field{margin-bottom:14px}
.field label{display:block;font-size:12px;font-weight:600;color:#94a3b8;text-transform:uppercase;letter-spacing:.5px;margin-bottom:6px}
.field input{width:100%;padding:12px 14px;background:#1e2535;border:1px solid rgba(255,255,255,.08);border-radius:10px;color:#e2e8f0;font-size:14px;font-family:inherit;outline:none;transition:border-color .2s}
.field input:focus{border-color:rgba(124,111,224,.5);box-shadow:0 0 0 3px rgba(124,111,224,.18)}
.btn{display:inline-block;padding:13px 22px;border-radius:12px;border:none;font-size:14px;font-weight:700;cursor:pointer;font-family:inherit;text-decoration:none;color:#fff;transition:opacity .2s,transform .15s}
.btn.primary{background:linear-gradient(135deg,#7c6fe0,#5b52c4);box-shadow:0 6px 16px rgba(100,80,220,.3)}
.btn.primary:hover{opacity:.9;transform:translateY(-1px)}
.btn.ghost{background:transparent;border:1px solid rgba(124,111,224,.35);color:#a78bfa}
.row{display:flex;gap:10px;justify-content:space-between;align-items:center;margin-top:18px}
.err{background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.3);border-radius:10px;padding:12px 14px;color:#fca5a5;font-size:13px;margin-bottom:14px}
.ok{background:rgba(52,211,153,.08);border:1px solid rgba(52,211,153,.3);border-radius:10px;padding:12px 14px;color:#6ee7b7;font-size:13px;margin-bottom:14px}
.check{display:flex;justify-content:space-between;padding:10px 14px;background:#1e2535;border:1px solid rgba(255,255,255,.05);border-radius:10px;margin-bottom:8px;font-size:13px}
.check .v{font-weight:700}
.check .v.ok{color:#34d399}
.check .v.no{color:#f87171}
.hint{font-size:12px;color:#5a6478;margin-top:4px;line-height:1.5}
code{background:rgba(124,111,224,.1);padding:2px 6px;border-radius:4px;color:#a78bfa;font-family:'SF Mono',monospace;font-size:12px}
.summary{background:#1e2535;border-radius:10px;padding:14px;margin:14px 0}
.summary div{padding:6px 0;display:flex;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.04);font-size:13px}
.summary div:last-child{border:0}
.summary div span:first-child{color:#94a3b8}
.summary div span:last-child{color:#e2e8f0;font-weight:600}
</style>
</head>
<body>
<div class="wrap">

<div class="head">
  <h1>HCLOU License</h1>
  <p>Cài đặt 5 bước — License server cho Lua/GameGuardian</p>
</div>

<div class="steps">
  <?php for ($i = 1; $i <= 5; $i++): ?>
    <div class="stepdot <?= $i <= $step ? 'on' : '' ?>"></div>
  <?php endfor ?>
</div>

<div class="card">

<?php if ($err): ?><div class="err">⚠ <?= h($err) ?></div><?php endif ?>
<?php if ($ok): ?><div class="ok">✓ <?= h($ok) ?></div><?php endif ?>

<?php if ($step === 1): // SYSTEM CHECK ?>
<h2>Bước 1: Kiểm tra hệ thống</h2>

<?php
$phpOk = version_compare(PHP_VERSION, '7.4.0', '>=');
$extPdo = extension_loaded('pdo_mysql');
$extMb  = extension_loaded('mbstring');
$extOpen= extension_loaded('openssl');
$writeData = is_writable(__DIR__ . '/data');
$writeRoot = is_writable(__DIR__);
$hasSchema = is_file($sqlFile);
?>
<div class="check"><span>PHP &ge; 7.4 (hiện <?= PHP_VERSION ?>)</span><span class="v <?= $phpOk?'ok':'no' ?>"><?= $phpOk?'✓':'✗' ?></span></div>
<div class="check"><span>Extension pdo_mysql</span><span class="v <?= $extPdo?'ok':'no' ?>"><?= $extPdo?'✓':'✗' ?></span></div>
<div class="check"><span>Extension mbstring</span><span class="v <?= $extMb?'ok':'no' ?>"><?= $extMb?'✓':'✗' ?></span></div>
<div class="check"><span>Extension openssl</span><span class="v <?= $extOpen?'ok':'no' ?>"><?= $extOpen?'✓':'✗' ?></span></div>
<div class="check"><span>Folder <code>data/</code> ghi được</span><span class="v <?= $writeData?'ok':'no' ?>"><?= $writeData?'✓':'✗' ?></span></div>
<div class="check"><span>Root folder ghi được (cho config.local.php)</span><span class="v <?= $writeRoot?'ok':'no' ?>"><?= $writeRoot?'✓':'✗' ?></span></div>
<div class="check"><span>File <code>database.sql</code></span><span class="v <?= $hasSchema?'ok':'no' ?>"><?= $hasSchema?'✓':'✗' ?></span></div>

<?php $allOk = $phpOk && $extPdo && $extMb && $extOpen && $writeData && $writeRoot && $hasSchema; ?>

<div class="row">
  <span></span>
  <?php if ($allOk): ?>
    <a class="btn primary" href="?step=2">Tiếp tục →</a>
  <?php else: ?>
    <div class="hint">Sửa các ✗ trên trước khi tiếp tục (PHP version, extension, chmod 755 folder, upload database.sql).</div>
  <?php endif ?>
</div>

<?php elseif ($step === 2): // DATABASE ?>
<h2>Bước 2: Database MySQL</h2>
<form method="POST">
  <input type="hidden" name="csrf" value="<?= h($_SESSION['install_csrf']) ?>">
  <input type="hidden" name="step" value="2">

  <div class="field">
    <label>DB Host</label>
    <input name="db_host" required value="<?= h($_POST['db_host'] ?? '127.0.0.1') ?>">
  </div>
  <div class="field">
    <label>DB Name</label>
    <input name="db_name" required value="<?= h($_POST['db_name'] ?? '') ?>" placeholder="hclou_license">
  </div>
  <div class="field">
    <label>DB User</label>
    <input name="db_user" required value="<?= h($_POST['db_user'] ?? '') ?>">
  </div>
  <div class="field">
    <label>DB Password</label>
    <input type="password" name="db_pass" value="<?= h($_POST['db_pass'] ?? '') ?>">
  </div>
  <div class="hint">Tạo DB trước trong cPanel/phpMyAdmin. Tao sẽ test connection trước khi qua bước sau.</div>
  <div class="row">
    <a class="btn ghost" href="?step=1">← Quay lại</a>
    <button class="btn primary" type="submit">Test &amp; Tiếp tục →</button>
  </div>
</form>

<?php elseif ($step === 3): // IMPORT SCHEMA ?>
<h2>Bước 3: Import schema</h2>
<?php $db = $_SESSION['install_data']['db'] ?? null; ?>
<?php if (!$db): ?>
  <div class="err">Mất config DB. Quay lại bước 2.</div>
  <a class="btn primary" href="?step=2">← Quay lại</a>
<?php else: ?>
  <div class="summary">
    <div><span>DB Host</span><span><?= h($db['host']) ?></span></div>
    <div><span>DB Name</span><span><?= h($db['name']) ?></span></div>
    <div><span>DB User</span><span><?= h($db['user']) ?></span></div>
  </div>
  <p style="font-size:13px;color:#94a3b8;margin-bottom:14px">Tao sẽ import <code>database.sql</code> tạo 6 table: games, scripts, license_keys, connect_logs, banned_devices, settings.</p>
  <form method="POST">
    <input type="hidden" name="csrf" value="<?= h($_SESSION['install_csrf']) ?>">
    <input type="hidden" name="step" value="3">
    <div class="row">
      <a class="btn ghost" href="?step=2">← Quay lại</a>
      <button class="btn primary" type="submit">Import schema →</button>
    </div>
  </form>
<?php endif ?>

<?php elseif ($step === 4): // ADMIN + SITE INFO ?>
<h2>Bước 4: Admin account</h2>
<form method="POST">
  <input type="hidden" name="csrf" value="<?= h($_SESSION['install_csrf']) ?>">
  <input type="hidden" name="step" value="4">

  <div class="field">
    <label>Site URL</label>
    <input name="site_url" required value="<?= h($_POST['site_url'] ?? $siteUrlAuto) ?>">
    <div class="hint">URL public của license server, không kèm dấu / cuối.</div>
  </div>
  <div class="field">
    <label>Site Name</label>
    <input name="site_name" required value="<?= h($_POST['site_name'] ?? 'HCLOU License') ?>">
  </div>
  <div class="field">
    <label>Admin Username</label>
    <input name="admin_user" required pattern="[A-Za-z0-9_]{3,32}" value="<?= h($_POST['admin_user'] ?? '') ?>">
    <div class="hint">3-32 ký tự, chỉ A-Z a-z 0-9 _</div>
  </div>
  <div class="field">
    <label>Admin Password</label>
    <input type="password" name="admin_pass" required minlength="8">
    <div class="hint">Ít nhất 8 ký tự. Sẽ lưu bcrypt hash vào config.local.php.</div>
  </div>
  <p style="font-size:12px;color:#5a6478;margin-top:10px">⓵ Secrets STATIC_WORD / HMAC_SECRET / BODY_XOR_BASE sẽ auto-generate.</p>
  <div class="row">
    <a class="btn ghost" href="?step=3">← Quay lại</a>
    <button class="btn primary" type="submit">Tạo config →</button>
  </div>
</form>

<?php elseif ($step === 5): // DONE ?>
<?php $sum = $_SESSION['install_data']['summary'] ?? []; ?>
<h2>✓ Cài đặt hoàn tất</h2>

<div class="ok">Đã tạo <code>config.local.php</code> + import schema (<?= (int)($sum['imported'] ?? 0) ?> statements) + khoá installer.</div>

<div class="summary">
  <div><span>Site URL</span><span><?= h($sum['site_url'] ?? '') ?></span></div>
  <div><span>Site Name</span><span><?= h($sum['site_name'] ?? '') ?></span></div>
  <div><span>Admin user</span><span><?= h($sum['admin_user'] ?? '') ?></span></div>
  <div><span>Lock file</span><span><code>data/installed.lock</code></span></div>
</div>

<div style="background:rgba(251,146,60,.08);border:1px solid rgba(251,146,60,.3);border-radius:10px;padding:14px;color:#fdba74;font-size:13px;margin:14px 0;line-height:1.6">
  <b>Bảo mật:</b> Xoá hoặc rename file <code>install.php</code> sau khi cài xong để chống dùng lại. File này đã tự khoá nhờ <code>data/installed.lock</code>, nhưng remove vẫn an toàn hơn.
</div>

<div class="row" style="justify-content:center;gap:12px">
  <a class="btn primary" href="admin/">→ Vào Admin Panel</a>
  <a class="btn ghost" href="index.php">JSON Info</a>
</div>

<?php endif ?>

</div>
</div>
</body>
</html>
<?php
// Wipe session sau step 5
if ($step === 5) {
    $_SESSION['install_data'] = [];
}
