
(30/325) Serial: FHVVTK0D35
   captcha OCR (lan 1/8): Đang giải mã...
   -> Mã gửi đi: FNYP
   [+] Đã gõ ENTER gửi mã...
   [!] Mã sai. Đang xóa trắng ô nhập và chờ Apple load ảnh mới...
   captcha OCR (lan 2/8): Đang giải mã...
   -> Mã gửi đi: ZBFA
   [+] Đã gõ ENTER gửi mã...

(31/325) Serial: GQXRY2YWCM
   captcha OCR (lan 1/8): Đang giải mã...
   [!] Mã OCR sai định dạng (ZNF - 3 ký tự). Bỏ qua, thử lại...
   captcha OCR (lan 2/8): Đang giải mã...
   [!] Mã OCR sai định dạng (ZNF - 3 ký tự). Bỏ qua, thử lại...
   captcha OCR (lan 3/8): Đang giải mã...
   [!] Mã OCR sai định dạng (ZNF - 3 ký tự). Bỏ qua, thử lại...
   captcha OCR (lan 4/8): Đang giải mã...
   [!] Mã OCR sai định dạng (ZNF - 3 ký tự). Bỏ qua, thử lại...
   captcha OCR (lan 5/8): Đang giải mã...
   [!] Mã OCR sai định dạng (ZNF - 3 ký tự). Bỏ qua, thử lại...
   captcha OCR (lan 6/8): Đang giải mã...
   [!] Mã OCR sai định dạng (ZNF - 3 ký tự). Bỏ qua, thử lại...
